# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CommonTableCollectView' do
pod 'CommonTableCollectView', :git => 'https://github.com/harde1/CommonTableCollectView'
end

target 'CommonTableCollectViewTests' do

end

target 'CommonTableCollectViewUITests' do

end

